### PR TITLE
font size now dependent on screen size

### PR DESCRIPTION
**Pull request by ytrellu**
Hi,

I am unfamiliar with css, but this is my current way of adapting the font size to smaller screens (in particular phones). I understand there are other ways of doing this, e.g. with https://css-tricks.com/viewport-sized-typography/. However I did not venture into this because of my unfamiliarity.

### CODE REVIEW

**Comment by kevquirk** [comment]
This isn't required as the font size is already dynamic using `rem` and the `--base-fontsize` variable.

**Comment by ytrellu** [comment]
Thanks for that info; 

The current font size is great for my desktop screen, however back on the phone I do need a bigger one (maybe something having to do with pixel density?).

So the current alternative for me will be to put this additional snippet in the html. This is not very elegant, and initially why I suggested this pull request.

**Comment by ytrellu** [comment]
I now learned about 

```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

and now it looks great on all tested screens. Sorry for this clumsiness and thanks for that css; I'll happily use it

**Comment by kevquirk** [comment]
Ah, yeah, if your site doesn't have that little snippet of meta, it won't be responsive. Glad you worked it out.

**Pull request closed without merging**
