### PR TITLE
Fix height issues in Chrome

### LINKED ISSUE #163: Height issues in Chrome (Webkit?)
This issue only appears in Chrome.
The size (height) of the elements are off when there's only few content on the page

image

### PR DESCRIPTION
**Pull request by darioackermann**
Resolves #163 
Not sure whether minification is automatically triggered?

### CODE REVIEW

**Comment by darioackermann** [comment]
Just realized this does not fix the issue completely. The header will have correct size but the rest of the content is still off

Left: Chrome, Right: Firefox
image

**Comment by darioackermann** [comment]
I'm unable to point it out at the moment, however adding `height: 0` to `body` works magically...

**Comment by darioackermann** [comment]
`align-content: start` works just fine.
Thanks for reviewing and merging.

**Comment by lkhrs** [comment]
Yes, we have an automatic minification step on the main branch.

I want to make sure we can reproduce the issue before merging, will discuss further in issue #163.

**Pull request closed without merging**
