### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fountainpen**

### CODE REVIEW

**Comment by lkhrs** [comment]
Related: #167 

I don’t think we should make these more visible. They are already documented in [Getting Started](https://github.com/kevquirk/simple.css/wiki/Getting-Started-With-Simple.css).

**Comment by fountainpen** [comment]
every single mini css demo has this because that way users can just come, copy-paste and use it on the fly:
https://okcss.netlify.app/

it's about making it accessible instantly, without any hassle, so you make user use YOUR product.

**Comment by waldyrious** [comment]
> I don’t think we should make these more visible.

Why not? :thinking: as I see it, it's a net positive to make the usage info more discoverable.

That said, I do like that the README is currently pretty bare and defers to the project website (https://simplecss.org/) for information, since that reduces the tendency to duplicate content. (In fact, I'd even suggest moving the "Supported Browsers" from the README into the website.)

So my suggestion would be to add these directly to the front page of the project: https://github.com/kevquirk/simple.css-site/blob/main/index.md

**Comment by kevquirk** [comment]
I think @lkhrs is right - we don't want duplicate content as it becomes a pain to maintain. I do think that we should make it as simple as possible for people to get to the Getting Started page though. With that in mind, I've added a button above the fold on the homepage.

Screenshot 2023-11-04 at 11 53 56

**Comment by fountainpen** [comment]
unsure how it adding links to YOUR product a pain to maintain. 🤷‍♂️

**Comment by kevquirk** [comment]
You don't understand how duplicate content is a pain to maintain?

If we have instructions on the documentation page, then on the README, then on the site itself too, that's 3 places we need to update any changes. Instead, if we all roads lead back to a single page, it's much easier to maintain.

**Comment by waldyrious** [comment]
> I'd even suggest moving the "Supported Browsers" from the README into the website.

Just so the thread doesn't get lost — any thoughts about this, @kevquirk?

**Comment by kevquirk** [comment]
The supported browsers thing was just a bit of fun really. None of the CSS in this stylesheet is particularly complicated of bleeding edge, so it's supported everywhere pretty much. I'm not against adding it to the site, I just don't see what value it would add.

**Comment by waldyrious** [comment]
In that case, would you be OK removing it from the README, just to make it extra clear that it's not meant to actually have independently maintained content? Not that it matters a lot to me, just trying to avoid future confusion like what led to this PR :)

**Pull request closed without merging**
